#     ___    __    ___   __________  __________________  __
#    /   |  / /   /   | / ____/ __ \/  _/_  __/_  __/\ \/ /
#   / /| | / /   / /| |/ /   / /_/ // /  / /   / /    \  / 
#  / ___ |/ /___/ ___ / /___/ _, _// /  / /   / /     / /  
# /_/  |_/_____/_/  |_\____/_/ |_/___/ /_/   /_/     /_/   
#
# https://github.com/jorgeloopzz  

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
normal.family = "SF Mono Powerline"
normal.style = "Medium"
bold.family = "SF Mono Powerline"
bold.style = "Bold"
size = 12

[window]
opacity = 0.8

[window.padding]
x = 6
y = 6

# Uncomment the theme you want
#import = [
	#"~/.config/alacritty/themes/catppuccin_macchiato.toml"
	#"~/.config/alacritty/themes/dracula.toml"
	#"~/.config/alacritty/themes/gruvbox_dark.toml"
    #"~/.config/alacritty/themes/onedark.toml"
	#"~/.config/alacritty/themes/rose-pine-moon.toml"
#]
# Colors (One Dark)

# Default colors
[colors.primary]
background = '#080808'
foreground = '#f0f0f0'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

