[window]
opacity = 0.9

padding.x = 8
padding.y = 8

[font]
normal.family = "MartianMono Nerd Font"
normal.style = "Medium"
bold.family = "MartianMono Nerd Font"
bold.style = "Bold"

size = 11

[cursor]
style.shape = "Beam"
style.blinking = "Always"
vi_mode_style.shape = "Block"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#c2c292"

[colors.cursor]
cursor = "#8e8e8e"
text = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#0A0A1B"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#b2ceee"
text = "#080808"
