[pyprland]
plugins = ["scratchpads", "lost_windows", "magnify", "expose"]

[expose]
include_special = false

[scratchpads.volume]
animation = "fromBottom"
command = "pavucontrol"
class = "pavucontrol"
lazy = false
size = "50% 60%"
unfocus = "hide"

[scratchpads.spotify]
animation = "fromTop"
command = "LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"
class = "Spotify"
process_tracking = false
lazy = true
size = "60% 70%"
unfocus = "hide"
match_by = "class"

[scratchpads.password]
animation = "fromTop"
command = "bitwarden-desktop"
class = "Bitwarden"
lazy = true
size = "50% 60%"
unfocus = "hide"
match_by = "class"
