return {
    "stevearc/conform.nvim",
    opts = {
        format_on_save = {
            timeout_ms = 1000,
            lsp_format = "fallback",
        },

        formatters_by_ft = {
            lua = { "stylua" },
            typescript = { "prettierd" },
            typescriptreact = { "prettierd" },
            javascript = { "prettierd" },
            javascriptreact = { "prettierd" },
            bash = { "shfmt" },
            css = { "prettierd" },
            java = { "astyle" },
            go = { "gofmt" },
            php = { "pint" },
            python = { "pyink" },
            rust = { "rustfmt" },
            c = { "clang-format" },
            cpp = { "clang-format" },
            cs = { "csharpier" },
            html = { "prettierd" },
            json = { "prettierd" },
            jsonc = { "prettierd" },
            sh = { "shfmt" },
            toml = { "taplo" },
            yaml = { "yamlfmt" },
            tex = { "latexindent" },
            xml = { "xmlformatter" },
            nix = { "alejandra" },
            typst = { "typstyle" },
        },
    },
}
